export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_LOADING_STATUS = 'LOGIN_LOADING_STATUS';
export const PICK_DATE_RANGE = 'PICK_DATE_RANGE';
export const DATE_FOCUSED = 'DATE_FOCUSED';
export const SET_FARMER_NUMBER_DROPDOWN_MENU =
  'OPEN_FARMER_NUMBER_DROPDOWN_MENU';
export const TOGGLE_DROPDOWN_MENU = 'TOGGLE_DROPDOWN_MENU';
export const SET_FILTER_ROLE = 'SET_FILTER_ROLE';
export const SHOW_USER_DETAILS = 'SHOW_USER_DETAILS';
export const ADD_ALL_USERS_TO_LIST = 'ADD_ALL_USERS_TO_LIST';
export const CLEAR_HIGHLIGHTED_USERS = 'CLEAR_HIGHLIGHTED_USERS';
export const SET_FARMER_DATA_FETCH_NUMBER = 'SET_FARMER_DATA_FETCH_NUMBER';
export const ADD_ALL_FARM_ITEMS = 'ADD_ALL_FARM_ITEMS';
export const ADD_SINGLE_ITEM = 'ADD_SINGLE_ITEM';
export const CLEAR_FARM_DATA = 'CLEAR_FARM_DATA';
export const DATA_LOADING_FALSE = 'DATA_LOADING_FALSE';
export const SET_PAGE_COUNT = 'SET_PAGE_COUNT';
export const DATA_LOADING_TRUE = 'DATA_LOADING_TRUE';
export const SET_USER_DATA_FETCH_AMOUNT = 'SET_USER_DATA_FETCH_AMOUNT';
export const FILTER_FETCH = 'FILTER_FETCH';
export const SET_FILTER_STATE = 'SET_FILTER_STATE';
export const REMOVE_SINGLE_ITEM = 'REMOVE_SINGLE_ITEM';
export const TOTAL_AVAILABLE_DATA = 'TOTAL_AVAILABLE_DATA';
export const CURRENT_PAGE = 'CURRENT_PAGE';
export const FETCH_FARMER_DATA = 'FETCH_FARMER_DATA';
export const DATA_LOADING = 'DATA_LOADING';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const HIGHLIGHT_A_USER = 'HIGHLIGHT_A_USER';
export const REMOVE_A_USER_HIGHLIGHT = 'REMOVE_A_USER_HIGHLIGHT';
export const GET_ALL_WALLETS_TRANSACTIONS = 'GET_ALL_WALLETS_TRANSACTIONS';
export const GET_ONE_WALLET_TRANSACTION = 'GET_ONE_WALLET_TRANSACTION';
export const SET_WALLET_DATA_FETCH_AMOUNT = 'SET_WALLET_DATA_FETCH_AMOUNT';
export const SET_TRANSACTION_STATUS_FETCH = 'SET_TRANSACTION_STATUS_FETCH';
export const GET_ALL_SERVICES_TRANSACTIONS = 'GET_ALL_SERVICES_TRANSACTIONS';
export const GET_ONE_SERVICE_TRANSACTION = 'GET_ONE_SERVICE_TRANSACTION';
export const SET_SERVICE_DATA_FETCH_AMOUNT = 'SET_SERVICE_DATA_FETCH_AMOUNT';
export const GET_ALL_ADMIN_SERVICES = 'GET_ALL_ADMIN_SERVICES';
export const SET_ADMIN_SERVICE_DATA_FETCH_AMOUNT =
  'SET_ADMIN_SERVICE_DATA_FETCH_AMOUNT';
export const GET_ALL_BANKS = 'GET_ALL_BANKS';
export const SAVE_ALL_FETCHED_COMMISSIONS_DATA =
  'SAVE_ALL_FETCHED_COMMISSIONS_DATA';
export const GET_A_COMMISSION_HISTORY = 'GET_A_COMMISSION_HISTORY';
export const SET_COMMISSION_DATA_FETCH_AMOUNT =
  'SET_COMMISSION_DATA_FETCH_AMOUNT';
export const GET_ALL_SWITCH_LOGS = 'GET_ALL_SWITCH_LOGS';
export const SET_MESSAGES_DATA_FETCH_AMOUNT = 'SET_MESSAGES_DATA_FETCH_AMOUNT';
export const SET_UPDATE_DATA_FETCH_AMOUNT = 'SET_UPDATE_DATA_FETCH_AMOUNT';
export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';
export const GET_ONE_MESSAGE = 'GET_ONE_MESSAGE';
export const UPDATE_ONE_MESSAGE = 'UPDATE_ONE_MESSAGE';
export const DELETE_ONE_MESSAGE = 'DELETE_ONE_MESSAGE';
export const GET_ALL_APPUPDATES = 'GET_ALL_APPUPDATES';
export const GET_ONE_UPDATE = 'GET_ONE_UPDATE';
export const SET_APP_UPDATE_DATA_FETCH_AMOUNT =
  'SET_APP_UPDATE_DATA_FETCH_AMOUNT';
export const GET_NEW_AGENTS = 'GET_NEW_AGENTS';
export const ONE_NEW_AGENTS = 'ONE_NEW_AGENTS';
export const SET_NEWAGENTS_DATA_FETCH_AMOUNT =
  'SET_NEWAGENTS_DATA_FETCH_AMOUNT';
export const GET_ALL_POS = 'GET_ALL_POS';
export const GET_ALL_TRANSACTIONS_ON_POS = 'GET_ALL_TRANSACTIONS_ON_POS';
export const GET_SINGLE_TRANSACTIONS_ON_POS = 'GET_SINGLE_TRANSACTIONS_ON_POS';
export const GET_ONE_POS = 'GET_ONE_POS';
export const SHOW_POS_DETAILS = 'SHOW_POS_DETAILS';
export const UPDATE_ONE_POS = 'UPDATE_ONE_POS';
export const DELETE_ONE_POS = 'DELETE_ONE_POS';
export const SET_POS_DATA_FETCH_AMOUNT = 'SET_POS_DATA_FETCH_AMOUNT';
export const SET_POS_DATA_FETCH_AMOUNT_POS_TRANX =
  'SET_POS_DATA_FETCH_AMOUNT_POS_TRANX';
export const GET_ALL_ISSUES = 'GET_ALL_ISSUES';
export const GET_ONE_ISSUE = 'GET_ONE_ISSUE';
export const SET_ISSUE_FETCH_AMOUNT = 'SET_ISSUE_FETCH_AMOUNT';
export const GET_ALL_PAYMENT_NOTIFICATION = 'GET_ALL_PAYMENT_NOTIFICATION';
export const GET_ONE_PAYMENT_NOTIFICATION = 'GET_ONE_PAYMENT_NOTIFICATION';
export const SET_PAYMENT_NOTIFICATION_FETCH_AMOUNT =
  'SET_PAYMENT_NOTIFICATION_FETCH_AMOUNT';
export const GET_ALL_POS_NOTIFICATION = 'GET_ALL_POS_NOTIFICATION';
export const GET_ONE_POS_NOTIFICATION = 'GET_ONE_WALLET_NOTIFICATION';
export const SET_POS_NOTIFICATION_FETCH_AMOUNT =
  'SET_POS_NOTIFICATION_FETCH_AMOUNT';
export const GET_ALL_POS_TRANSACTION = 'GET_ALL_POS_TRANSACTION';
export const GET_ONE_POS_TRANSACTION = 'GET_ONE_POS_TRANSACTION';
export const SET_POS_TRANSACTION_FETCH_AMOUNT =
  'SET_POS_TRANSACTION_FETCH_AMOUNT';
